### ISSUE TITLE
some code are still obfuscated.

### ISSUE THREAD

**Issue by tas33n** [Yvainix/JSDefender-Deobfuscator#2]
i tried to deobfuscate a file but half of the code are still obfuscate and i dont understand how to solve that, i u could pls help me with this!!

![image](https://github.com/0v41n/JSDefender-Deobfuscator/assets/55633040/6cce8657-802e-4365-900d-ef230f8caf5c)

**Comment by 0v41n** [comment]
I apologise for taking so long to reply... I will fix this problem in the next few days. I also saw your email, would it be possible to send me the obfuscated code that creates this bug by email so that it can help me fix the problem?

**Comment by 0v41n** [comment]
basically it's a regex problem it seems, but I'll look at it in more detail tomorrow or the next day

**Comment by tas33n** [comment]
> I apologise for taking so long to reply... I will fix this problem in the next few days. I also saw your email, would it be possible to send me the obfuscated code that creates this bug by email so that it can help me fix the problem?

i replied the mail with the file link. please check it.

**Comment by 0v41n** [comment]
Good evening, I've just fixed the bugs as best I could, I hope I've fixed them completely, if not I'll continue to fix them.

**Comment by tas33n** [comment]
> Good evening, I've just fixed the bugs as best I could, I hope I've fixed them completely, if not I'll continue to fix them.

thank u so much for your heard work. i've already chekd it and its working fine now. tnx alot for fixing it.
